_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
